#!/bin/bash

###############################################################################
# Letters App - Replit Setup Script
# This script automates the setup process for deploying Letters on Replit
# Run this in your Replit shell: bash setup-replit.sh
###############################################################################

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Color codes for better output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Helper functions
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
print_step() { echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; echo -e "${BLUE}📋 $1${NC}"; echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"; }

# Banner
clear
echo -e "${BLUE}"
cat << "EOF"
╔═══════════════════════════════════════════════════════╗
║                                                       ║
║          ✉️  LETTERS APP - REPLIT SETUP              ║
║                                                       ║
║     Where Email Meets Elegance - Production Ready    ║
║                                                       ║
╚═══════════════════════════════════════════════════════╝
EOF
echo -e "${NC}\n"

###############################################################################
# Step 1: Pre-flight Checks
###############################################################################
print_step "Step 1: Pre-flight Checks"

# Check Node.js version
print_info "Checking Node.js version..."
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed!"
    exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 16 ]; then
    print_error "Node.js 16+ required. Current: $(node -v)"
    print_info "Please upgrade Node.js in Replit settings"
    exit 1
fi
print_success "Node.js version: $(node -v)"

# Check npm
print_info "Checking npm..."
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed!"
    exit 1
fi
print_success "npm version: $(npm -v)"

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    print_error "package.json not found! Are you in the project root?"
    exit 1
fi
print_success "Project root detected"

# Check if Prisma schema exists
if [ ! -f "prisma/schema.prisma" ]; then
    print_error "Prisma schema not found at prisma/schema.prisma"
    exit 1
fi
print_success "Prisma schema found"

###############################################################################
# Step 2: Install Dependencies
###############################################################################
print_step "Step 2: Installing Dependencies"

print_info "This may take a few minutes..."
if npm install --legacy-peer-deps 2>&1 | tee /tmp/npm-install.log; then
    print_success "Dependencies installed successfully"
else
    print_error "Failed to install dependencies"
    print_info "Check /tmp/npm-install.log for details"
    exit 1
fi

###############################################################################
# Step 3: Environment Configuration
###############################################################################
print_step "Step 3: Environment Configuration"

# Detect Replit environment
if [ -n "${REPL_SLUG:-}" ] && [ -n "${REPL_OWNER:-}" ]; then
    REPLIT_URL="https://${REPL_SLUG}.${REPL_OWNER}.repl.co"
    print_success "Replit environment detected"
    print_info "Your app URL: ${REPLIT_URL}"
else
    REPLIT_URL="https://your-repl.replit.dev"
    print_warning "Replit environment variables not detected"
    print_info "Using placeholder URL. Update manually in .env.local"
fi

# Generate NEXTAUTH_SECRET if not exists
if command -v openssl &> /dev/null; then
    NEXTAUTH_SECRET=$(openssl rand -base64 32 | tr -d '\n')
else
    # Fallback: use Node.js to generate secret
    NEXTAUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
fi

# Create .env.local if it doesn't exist
if [ ! -f ".env.local" ]; then
    print_info "Creating .env.local file..."
    
    cat > .env.local << EOF
# ============================================
# Letters App - Environment Configuration
# ============================================
# Generated by setup-replit.sh on $(date)

# Database Configuration
# For SQLite (development):
DATABASE_URL="file:./dev.db"

# For PostgreSQL (production - uncomment and configure):
# DATABASE_URL="postgresql://user:password@host:5432/dbname"

# NextAuth Configuration
NEXTAUTH_URL="${REPLIT_URL}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"

# Application Environment
NODE_ENV="production"
PORT="3000"

# Optional: Email Service Configuration
# Uncomment and configure when ready:
# RESEND_API_KEY=""
# GMAIL_CLIENT_ID=""
# GMAIL_CLIENT_SECRET=""
# GOOGLE_CLIENT_ID=""
# GOOGLE_CLIENT_SECRET=""

# Optional: File Storage
# BLOB_READ_WRITE_TOKEN=""

# Optional: Rate Limiting (Upstash Redis)
# UPSTASH_REDIS_REST_URL=""
# UPSTASH_REDIS_REST_TOKEN=""
EOF
    
    print_success ".env.local created"
    print_warning "IMPORTANT: Review .env.local and update if needed"
    print_info "For production, move secrets to Replit Secrets tab (🔒 icon)"
else
    print_info ".env.local already exists, skipping creation"
    print_warning "Make sure NEXTAUTH_URL and NEXTAUTH_SECRET are set correctly"
fi

###############################################################################
# Step 4: Prisma Setup
###############################################################################
print_step "Step 4: Prisma Database Setup"

# Generate Prisma Client
print_info "Generating Prisma Client..."
if npx prisma generate; then
    print_success "Prisma Client generated"
else
    print_error "Failed to generate Prisma Client"
    exit 1
fi

# Check if database file exists (for SQLite)
if [ -f "prisma/dev.db" ]; then
    print_info "Database file exists, checking migrations..."
    # Try to run migrations (may fail if already applied, that's OK)
    npx prisma migrate dev --name init 2>&1 | grep -v "already applied" || true
else
    print_info "Running initial database migration..."
    if npx prisma migrate dev --name init; then
        print_success "Database migrations completed"
    else
        print_warning "Migration may have already run or encountered an issue"
        print_info "This is usually OK if the database already exists"
    fi
fi

# Verify database connection
print_info "Verifying database connection..."
if npx prisma db pull --force 2>&1 | grep -q "Introspecting"; then
    print_success "Database connection verified"
else
    print_warning "Could not verify database connection"
    print_info "This may be OK if using a new database"
fi

###############################################################################
# Step 5: Build Verification
###############################################################################
print_step "Step 5: Build Verification"

print_info "Building the project (this may take a minute)..."
if npm run build 2>&1 | tee /tmp/build.log; then
    print_success "Build completed successfully"
else
    print_error "Build failed!"
    print_info "Check /tmp/build.log for details"
    print_warning "You can still run 'npm run dev' for development"
    # Don't exit on build failure - dev mode might still work
fi

###############################################################################
# Step 6: Final Checks & Summary
###############################################################################
print_step "Step 6: Final Checks"

# Check critical files
CRITICAL_FILES=(
    "package.json"
    "prisma/schema.prisma"
    ".env.local"
    "next.config.ts"
)

MISSING_FILES=()
for file in "${CRITICAL_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        MISSING_FILES+=("$file")
    fi
done

if [ ${#MISSING_FILES[@]} -eq 0 ]; then
    print_success "All critical files present"
else
    print_warning "Missing files: ${MISSING_FILES[*]}"
fi

# Check .replit file
if [ ! -f ".replit" ]; then
    print_warning ".replit file not found"
    print_info "Creating basic .replit configuration..."
    cat > .replit << 'EOF'
language = "nodejs"
run = "npm run dev"

[env]
NODE_ENV = "production"

[deploy]
run = ["sh", "-c", "npm run build && npm start"]
publicDir = ".next"
EOF
    print_success ".replit file created"
fi

###############################################################################
# Success Summary
###############################################################################
echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}║              ✅ SETUP COMPLETE!                      ║"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""

print_info "Next Steps:"
echo ""
echo "  1. 🔐 Configure Secrets (IMPORTANT):"
echo "     • Go to Replit Secrets tab (🔒 icon)"
echo "     • Add: DATABASE_URL, NEXTAUTH_URL, NEXTAUTH_SECRET"
echo "     • Secrets override .env.local values"
echo ""
echo "  2. 🗄️  Database Options:"
echo "     • SQLite (current): file:./dev.db"
echo "     • Replit DB: Use Replit Database"
echo "     • PostgreSQL: Use Supabase/Neon/Railway"
echo ""
echo "  3. ▶️  Start Development:"
echo "     • Run: npm run dev"
echo "     • Or click 'Run' button in Replit"
echo ""
echo "  4. 🌐 Access Your App:"
if [ -n "${REPLIT_URL:-}" ]; then
    echo "     • URL: ${REPLIT_URL}"
else
    echo "     • URL: https://your-repl.replit.dev"
fi
echo ""
echo "  5. 📚 Documentation:"
echo "     • Full guide: ./REPLIT_DEPLOYMENT.md"
echo "     • Quick ref: ./REPLIT_QUICK_START.md"
echo ""

print_warning "Security Reminder:"
echo "  • Never commit .env.local to git"
echo "  • Use Replit Secrets for production"
echo "  • Rotate NEXTAUTH_SECRET regularly"
echo ""

print_info "Troubleshooting:"
echo "  • Build issues? Run: rm -rf .next node_modules && npm install"
echo "  • Database errors? Check DATABASE_URL in Secrets"
echo "  • Port conflicts? Replit handles ports automatically"
echo ""

echo -e "${GREEN}Happy coding! 🚀${NC}"
echo ""

